vich_uploader:
    db_driver: orm
    metadata: 
        type: attribute

    mappings:
       article_image:
           uri_prefix: /images/article
           upload_destination: '%kernel.project_dir%/public/images/article'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
